# HUGO configuration
baseURL: 'https://horvathzoltan.me/'
languageCode: en
defaultContentLanguage: en
title: "HorvathZoltan.me"
copyright: "© 2024 [Horváth Zoltán](https://horvathzoltan.me) [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0)"

enableRobotsTXT: true
enableEmoji: true

pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: About Me
      url: "/about/"
      weight: 5
    # - identifier: resume
    #   name: Resume
    #   url: "/resume"
    #   weight: 10
    - identifier: cloud
      name: Private cloud
      url: "https://dash.horvathzoltan.me/"
      weight: 15

theme:
  - github.com/martignoni/hugo-notice
  - github.com/adityatelange/hugo-PaperMod
  # - github.com/jpanther/congo/v2


module:
  imports:
    - path: github.com/martignoni/hugo-notice
    - path: github.com/adityatelange/hugo-PaperMod
    # - path: github.com/jpanther/congo/v2

params:
  env: production
  defaultTheme: light
  disableThemeToggle: true
  ShowCodeCopyButtons: true
  DateFormat: "2006-01-02"
  # ShowReadingTime: true
  # ShowBreadCrumbs: true
  # author: "Horváth Zoltán"

  assets:
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/favicon-apple-touch-icon.png"

  label:
    icon: "/img/HZ_logo.png"

  profileMode:
    enabled: true
    title: "Horváth Zoltán"
    subtitle: "Solution Architect  |  Apple Certified Support Professional"
    # subtitle: "Hi there! \U0001F44B </br> Welcome to my website."
    imageUrl: "/img/HZ_circular_avatar_bw.png"
    imageTitle: "Horváth Zoltán"
    imageWidth: 180
    imageHeight: 180
    buttons:
      - identifier: about
        name: About Me
        url: "/about"
      # - identifier: resume
      #   name: Resume
      #   url: "/resume"
      - identifier: cloud
        name: Private cloud
        url: "https://dash.horvathzoltan.me/"

  social: true
  socialIcons:
    # - name: CV
    #   url: "/resume.pdf"
    - name: linkedin
      title: LinkedIn
      url: 'https://www.linkedin.com/in/zhorvath83'
    - name: github
      title: GitHub
      url: 'https://github.com/zhorvath83'
    - name: codepen
      title: My tech stack
      url: 'https://stackshare.io/zhorvath83/my-stack'
    - name: email
      title: Mail me
      url: 'mailto:contact@horvathzoltan.me'
