# HUGO configuration
baseURL: 'https://¤{ROOT_DOMAIN}/'
googleAnalytics: ''
languageCode: hu
defaultContentLanguage: hu
title: Zoltán Horváth
theme: hermit
pygmentsCodefences: true
pygmentsUseClasses: true
rssLimit: 10
copyright: ''
enableEmoji: true
disableKinds: RSS
author:
  name: Zoltán Horváth
blackfriday: {}
# do not create any taxonomies
disableKinds:
  - section
  - taxonomyTerm
  - taxonomy
  - RSS
  - sitemap
  - robotsTXT
  - 404
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  themeColor: '#0a3d62'
  bgImg: /img/background.png
  homeSubtitle: ''
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  justifyContent: true
  relatedPosts: false
  code_copy_button: true
  customCSS:
    - css/style.css
  social:
    - name: linkedin
      url: 'https://www.linkedin.com/in/zhorvath83'
    - name: github
      url: 'https://github.com/zhorvath83'
    - name: stackshare
      url: 'https://stackshare.io/zhorvath83/my-stack'
    - name: email
      url: 'mailto:¤{PROJECT_OWNER_EMAIL}'
menu:
  main:
    - name: Resume
      url: resume/
      weight: 10
      pre: <i class='fa-regular fa-address-card'></i>
    - name: Login
      url: 'https://dash.¤{ROOT_DOMAIN}'
      weight: 20
      pre: <i class='fa-regular fa-right-to-bracket'></i>