# HUGO configuration
baseURL: 'https://¤{ROOT_DOMAIN}/'
title: Zoltán Horváth
theme: ["hugo-cloak-email", "hugo-coder"]
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
disableKinds:
  - section
  - taxonomyTerm
  - taxonomy
  - RSS
  - sitemap
  - robotsTXT
  - 404
params:
  author: Zoltán Horváth
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  description: Zoltán Horváth's personal website
  keywords: personal
  info: []
  avatarURL: images/avatar.jpg
  dateFormat: January 2, 2006
  since: 2020
  commit: https://github.com/zhorvath83/private-website
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []
  csp:
    childsrc:
      - "'self'"
    fontsrc:
      - "'self'"
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction:
      - "'self'"
    framesrc:
      - "'self'"
    imgsrc:
      - "'self'"
    objectsrc:
      - "'none'"
    stylesrc:
      - "'self'"
      - "'unsafe-inline'"
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
    scriptsrc:
      - "'self'"
      - "'unsafe-inline'"
      - https://www.google-analytics.com
      - https://cdn.jsdelivr.net/
    prefetchsrc:
      - "'self'"
    connectsrc:
      - "'self'"
      - https://www.google-analytics.com
  social:
    - name: Github
      icon: fa fa-2x fa-github
      weight: 1
      url: https://github.com/zhorvath83
    - name: LinkedIn
      icon: fa fa-2x fa-linkedin
      weight: 2
      url: https://www.linkedin.com/in/zhorvath83
    - name: Stackshare
      icon: fa fa-2x fa-stack-exchange
      weight: 3
      url: https://stackshare.io/zhorvath83/my-stack
    - name: RSS
      icon: fa fa-2x fa-file-user
      weight: 4
      url: resume/

languages:
  en:
    languageName: ":EN:"
    menu:
      main:
        - name: Login
          weight: 1
          url: https://dash.¤{ROOT_DOMAIN}
        - name: Resume
          weight: 2
          url: resume/
        - name: Contact me
          weight: 3
          url: contact/
  hu:
    languageName: ":HU:"
    title: Horváth Zoltán
    params:
      author: Horváth Zoltán
      info: []
      description: Horváth Zoltán honlapja
    menu:
      main:
        - name: Bejelentkezés
          weight: 1
          url: https://dash.¤{ROOT_DOMAIN}
        - name: CV
          weight: 2
          url: resume/
        - name: Kapcsolat
          weight: 3
          url: contact/
