name: Deploy private-website to Netlify

on:
  workflow_dispatch:

jobs:
  building-private-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout hugo-cloak-email repository
        uses: actions/checkout@v3
        with:
          repository: martignoni/hugo-cloak-email
          path: themes/hugo-cloak-email

      - name: Checkout theme repository
        uses: actions/checkout@v3
        with:
          repository: Track3/hermit
          path: themes/hermit

      # - name: Replace variables
      #   uses: cschleiden/replace-tokens@v1
      #   with:
      #     tokenPrefix: '¤{'
      #     tokenSuffix: '}'
      #     files: '["**/config.yaml","**/resume.json"]'
      #   env:
      #     PROJECT_OWNER_EMAIL: ${{ secrets.PROJECT_OWNER_EMAIL }}
      #     PROJECT_OWNER_PHONE:  ${{ secrets.PROJECT_OWNER_PHONE }}
      #     ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}

      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: macchiato
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: content/resume/index.html

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # renovate: datasource=github-releases depName=gohugoio/hugo
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './public'
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
